language: go

go:
  - 1.9.x

script:
- go build -o build/resec_linux_amd64_${TRAVIS_BRANCH}
- zip -j build/resec_linux_amd64_${TRAVIS_BRANCH}.zip build/resec_linux_amd64_${TRAVIS_BRANCH}
deploy:
  if: tag =~ ^v.*
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Y5PuKVV8732JTNQuZFb/wkzueEd4E6syn+1+9x2Iz+Jx3pqDx2xCXFMDlBFyG4PBHOOir7kU09wClhKZNjQMDwKg24mPS5dCnCkc70hjhzlzJ+dfRReDDkv8f8L/ZMFXi+als2q4OSYcq8sedn5pEBNMVhUAhRm63Lce4MlNmB+rRMPjDffE3dEXVtKRvjX/wMCVOQPgUid8or7on22Qzcn1K8i4XYG2eUgGe4ztrnCOzDYfOnzgV3sUukra7oECwCTOhDXE6WgF1VfhRbKwetAtd19+gklKHQp4hueWmzIoyHxCflXP4CbBuS/6OyLCb2DgIc1CvtvW446zm9MJG1t5onRHaQCRaj53UteDH1q0DtfXJV4Ks1le84giVYwMbMP6lne93KVd95yKycSJO02shlaDbfyXMEkFyQlzs4xhb11dlVSqhw1PvnBIIvfDSiIi/y6sCEwZNpTNYG8/qgNUHQKhzXdXolIwwWcxILRUciygp04jRyI4HzNx5xm43DWr3vSMD6I6f/4CcczzrDAwMOEtoYJ1HjKOKrrRk/AqakySzupP/HIhmb/3R/GFch/9YkcnzUcCaGboudQjs0faERGlzlZ+oliXS/O5dCOzoD6+rY/DPapIKdoCzoeod0j+o94VAbLmwoO20ACqURfuYs0n6+nG2qbe2pshnSM=
  file_glob: true
  file: build/*.zip
  on:
    repo: YotpoLtd/resec
    branch: master
    tags: true
